title = "De los Andes"
baseURL = "https://carloshs92.github.io/breakfast-landing/"
languageCode = "en-us"
theme = "airspace-hugo"

# The site's parameters
[params]
  home = "Inicio"

  [menu]

    [[menu.header]]
      weight = 5
      name = "Quiero saber más"
      url = "/contact"

    [[menu.footer]]
      weight = 1
      name = "Términos y condiciones"
      url = "#"

  [params.slider]
    enable = true
    title = "El desayuno que tu deseas"
    subtitle = "Recibe tu pedido de manera rápida y personalizada"
    bgImage = "img/slider-background.jpg?v=1.0"
    btnText = ""
    url = "#"

  [params.wrapper]
    enable = true
    image = "img/wrapper-image.jpg?v=1.1"
    title = "Quienes Somos"
    italic = "El desayuno es la única comida del día que se tiende a ver con el mismo tipo de reverencia tradicional como la que la mayoría de la gente asocia con el almuerzo y la cena."
    paragraph = "Somos personas apasionadas por la buena comida y la salud de las personas. Queremos llegar a contribuir a que se inicie con energía cada día ofreciendo desayunos que disfruten de inicio a fin."


  [params.feature]
    enable = true
    title = "¿Cómo es tu desayuno ideal?"
    bgImage = "img/feature-background.jpg?v=1.0"
    content = "Elige entre una gran variedad de desayunos: <ul><li style='color: #8d8f92;list-style-type: circle;'>Emoliente, Maca, Quinua, Avena, Yogurt y 7 Semillas</li><li style='color: #8d8f92;list-style-type: circle;'>Pan chapla, francés e integral</li><li style='color: #8d8f92;list-style-type: circle;'>Palta, tamal, huevos, tortillas con espinaca, queso, pollo, salchicha, queso fresco</li> <br/> <span style='color: #8d8f92;list-style-type: circle;'>¡Disfrútalos! Todos los productos son frescos y a un buen precio.</span>"

  [params.call]
    enable = false
    bgImage = "img/call-to-action-bg.jpg"
    title = ""
    paragraph = ""

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
