title = "De los Andes"
baseURL = "https://carloshs92.github.io/breakfast-landing/"
languageCode = "en-us"
theme = "airspace-hugo"

# The site's parameters
[params]
  home = "Inicio"

  [menu]

    [[menu.header]]
      weight = 5
      name = "Quiero saber más"
      url = "/contact"

    [[menu.footer]]
      weight = 1
      name = "Términos y condiciones"
      url = "#"

  [params.slider]
    enable = true
    title = "El desayuno que deseas"
    subtitle = "Tú decides que desayunar.<br/>Recibe tu pedido de manera rápida y personalizada"
    bgImage = "img/slider-background.png?v=1.0"
    btnText = ""
    url = "#"

  [params.wrapper]
    enable = true
    image = "img/wrapper-img.jpg"
    title = "Quienes Somos"
    italic = "El desayuno es la única comida del día que se tiende a ver con el mismo tipo de reverencia tradicional como la que la mayoría de la gente asocia con el almuerzo y la cena."
    paragraph = "Somos personas apasionadas por la buena comida y la nutrición de las personas y queremos ayudar a las personas a que inicien bien cada día con un desayuno balanceado que puedan disfrutar de inicio a fin."


  [params.feature]
    enable = true
    title = "Un desayuno para cada uno"
    bgImage = "img/feature-backgrounds.jpg?v=1.0"
    content = "Disfruta de nuestra gran variedad de desayunos como el combo 'levanta muertos', 'choque y fuga', 'el sport', 'el vegetariano', 'el marinero', 'el mañanero'. <br/> Estos desayunos son altamente nutritivos y a un buen precio."

  [params.call]
    enable = false
    bgImage = "img/call-to-action-bg.jpg"
    title = "Un buen día inicia con un buen desayuno."
    paragraph = ""

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
